-- KSTP Cakung — Sistem Informasi & Layanan Warga
-- All tables use INTEGER ids generated by the application (UUID-ish strings)
-- to keep the schema portable and explicit.

-- ----- Residents (warga) -----
CREATE TABLE IF NOT EXISTS residents (
  id TEXT PRIMARY KEY,
  nama TEXT NOT NULL,
  username TEXT UNIQUE,
  foto TEXT,
  no_hp TEXT NOT NULL,
  email TEXT,
  tanggal_lahir TEXT,
  jenis_kelamin TEXT,
  blok TEXT NOT NULL,
  lantai TEXT NOT NULL,
  nomor_unit TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pemilik',          -- Pemilik | Penyewa | Keluarga
  account_status TEXT NOT NULL DEFAULT 'Belum Aktivasi', -- Belum Aktivasi | Aktif | Nonaktif
  role TEXT NOT NULL DEFAULT 'warga',              -- warga | pengelola | petugas_keuangan | petugas_keamanan | super_admin
  password_hash TEXT,
  invitation_code TEXT UNIQUE,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX IF NOT EXISTS idx_residents_invitation ON residents(invitation_code);
CREATE INDEX IF NOT EXISTS idx_residents_username ON residents(username);
CREATE INDEX IF NOT EXISTS idx_residents_role ON residents(role);

-- ----- Announcements -----
CREATE TABLE IF NOT EXISTS announcements (
  id TEXT PRIMARY KEY,
  judul TEXT NOT NULL,
  isi TEXT NOT NULL,
  kategori TEXT NOT NULL CHECK (kategori IN ('Umum','Penting','Darurat')),
  tanggal TEXT NOT NULL,
  penulis TEXT NOT NULL,
  author_id TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Obituaries -----
CREATE TABLE IF NOT EXISTS obituaries (
  id TEXT PRIMARY KEY,
  nama_almarhum TEXT NOT NULL,
  unit TEXT NOT NULL,
  lokasi_rumah_duka TEXT NOT NULL,
  jadwal_pemakaman TEXT NOT NULL,
  tanggal TEXT NOT NULL,
  catatan TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Dues (iuran) -----
CREATE TABLE IF NOT EXISTS dues (
  id TEXT PRIMARY KEY,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  jenis TEXT NOT NULL CHECK (jenis IN ('IPL','Kebersihan','Keamanan','Dana Sosial')),
  periode TEXT NOT NULL,
  jumlah INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'Belum Bayar' CHECK (status IN ('Belum Bayar','Menunggu Verifikasi','Lunas')),
  jatuh_tempo TEXT NOT NULL,
  payment_method TEXT,
  paid_at INTEGER,
  verified_by TEXT,
  verified_at INTEGER,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX IF NOT EXISTS idx_dues_resident ON dues(resident_id);
CREATE INDEX IF NOT EXISTS idx_dues_status ON dues(status);

-- ----- Transactions (transparansi keuangan) -----
CREATE TABLE IF NOT EXISTS transactions (
  id TEXT PRIMARY KEY,
  tanggal TEXT NOT NULL,
  keterangan TEXT NOT NULL,
  kategori TEXT NOT NULL,
  tipe TEXT NOT NULL CHECK (tipe IN ('pemasukan','pengeluaran')),
  jumlah INTEGER NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX IF NOT EXISTS idx_transactions_tanggal ON transactions(tanggal);

-- ----- Marketplace products -----
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  seller_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  nama TEXT NOT NULL,
  foto TEXT,
  harga INTEGER NOT NULL,
  stok INTEGER NOT NULL DEFAULT 0,
  deskripsi TEXT,
  kategori TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Marketplace orders -----
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  buyer_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  jumlah INTEGER NOT NULL DEFAULT 1,
  total INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'Menunggu Pembayaran' CHECK (status IN ('Menunggu Pembayaran','Diproses','Dikirim','Selesai')),
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Complaints (pengaduan) -----
CREATE TABLE IF NOT EXISTS complaints (
  id TEXT PRIMARY KEY,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  kategori TEXT NOT NULL CHECK (kategori IN ('Kebersihan','Keamanan','Infrastruktur','Fasilitas')),
  judul TEXT NOT NULL,
  deskripsi TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Baru' CHECK (status IN ('Baru','Diproses','Selesai')),
  tanggal TEXT NOT NULL,
  foto TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Panic alerts -----
CREATE TABLE IF NOT EXISTS panic_alerts (
  id TEXT PRIMARY KEY,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  jenis TEXT NOT NULL CHECK (jenis IN ('Medis','Kebakaran','Keamanan')),
  status TEXT NOT NULL DEFAULT 'Aktif' CHECK (status IN ('Aktif','Ditangani','Selesai')),
  waktu INTEGER NOT NULL DEFAULT (unixepoch()),
  handled_by TEXT,
  handled_at INTEGER
);

-- ----- Chat groups -----
CREATE TABLE IF NOT EXISTS chat_groups (
  id TEXT PRIMARY KEY,
  nama TEXT NOT NULL,
  deskripsi TEXT,
  icon_key TEXT NOT NULL DEFAULT 'users',
  is_main INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Chat group memberships -----
CREATE TABLE IF NOT EXISTS chat_group_members (
  group_id TEXT NOT NULL REFERENCES chat_groups(id) ON DELETE CASCADE,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  joined_at INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY (group_id, resident_id)
);

-- ----- Chat messages (group + private unified) -----
CREATE TABLE IF NOT EXISTS chat_messages (
  id TEXT PRIMARY KEY,
  group_id TEXT REFERENCES chat_groups(id) ON DELETE CASCADE,  -- null for private chat
  sender_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  recipient_id TEXT REFERENCES residents(id) ON DELETE CASCADE, -- null for group chat
  isi TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX IF NOT EXISTS idx_messages_group ON chat_messages(group_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_private ON chat_messages(sender_id, recipient_id, created_at);

-- ----- Community feed posts -----
CREATE TABLE IF NOT EXISTS feed_posts (
  id TEXT PRIMARY KEY,
  author_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  kategori TEXT NOT NULL CHECK (kategori IN ('Informasi','Jual Beli','Kehilangan','Lowongan Kerja','Aktivitas Warga')),
  isi TEXT NOT NULL,
  gambar TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS feed_likes (
  post_id TEXT NOT NULL REFERENCES feed_posts(id) ON DELETE CASCADE,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY (post_id, resident_id)
);

CREATE TABLE IF NOT EXISTS feed_comments (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES feed_posts(id) ON DELETE CASCADE,
  author_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  isi TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Skill providers -----
CREATE TABLE IF NOT EXISTS skill_providers (
  id TEXT PRIMARY KEY,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  kategori TEXT NOT NULL,
  deskripsi TEXT,
  available INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS skill_reviews (
  id TEXT PRIMARY KEY,
  provider_id TEXT NOT NULL REFERENCES skill_providers(id) ON DELETE CASCADE,
  reviewer_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  komentar TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS skill_portfolios (
  id TEXT PRIMARY KEY,
  provider_id TEXT NOT NULL REFERENCES skill_providers(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Events -----
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  nama TEXT NOT NULL,
  tipe TEXT NOT NULL CHECK (tipe IN ('Kerja Bakti','Bazar','Pengajian','Senam','Perlombaan')),
  deskripsi TEXT,
  tanggal TEXT NOT NULL,
  waktu TEXT NOT NULL,
  lokasi TEXT NOT NULL,
  kuota INTEGER NOT NULL DEFAULT 0,
  foto TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS event_rsvp (
  event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  attended INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY (event_id, resident_id)
);

-- ----- Facilities & bookings -----
CREATE TABLE IF NOT EXISTS facilities (
  id TEXT PRIMARY KEY,
  nama TEXT NOT NULL,
  tipe TEXT NOT NULL CHECK (tipe IN ('Aula','Lapangan','Gazebo','Ruang Serbaguna')),
  deskripsi TEXT,
  kapasitas INTEGER NOT NULL DEFAULT 0,
  foto TEXT,
  jam_operasional TEXT
);

CREATE TABLE IF NOT EXISTS bookings (
  id TEXT PRIMARY KEY,
  facility_id TEXT NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  tanggal TEXT NOT NULL,
  waktu TEXT NOT NULL,
  keperluan TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected','Finished')),
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- E-Voting -----
CREATE TABLE IF NOT EXISTS votings (
  id TEXT PRIMARY KEY,
  judul TEXT NOT NULL,
  tipe TEXT NOT NULL CHECK (tipe IN ('Pemilihan Ketua','Musyawarah','Persetujuan Program')),
  deskripsi TEXT,
  status TEXT NOT NULL DEFAULT 'Berlangsung' CHECK (status IN ('Berlangsung','Selesai')),
  berakhir TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS voting_options (
  id TEXT PRIMARY KEY,
  voting_id TEXT NOT NULL REFERENCES votings(id) ON DELETE CASCADE,
  label TEXT NOT NULL
);

-- 1 unit = 1 suara — enforced by unique constraint on (voting, blok+lantai+nomor)
CREATE TABLE IF NOT EXISTS voting_ballots (
  id TEXT PRIMARY KEY,
  voting_id TEXT NOT NULL REFERENCES votings(id) ON DELETE CASCADE,
  option_id TEXT NOT NULL REFERENCES voting_options(id) ON DELETE CASCADE,
  unit_key TEXT NOT NULL,            -- "{blok}-{lantai}-{nomor}"
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE(voting_id, unit_key)
);

-- ----- Crowdfunding -----
CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  judul TEXT NOT NULL,
  tipe TEXT NOT NULL CHECK (tipe IN ('Renovasi','Bantuan Sosial','Perbaikan Fasilitas')),
  deskripsi TEXT,
  foto TEXT,
  target INTEGER NOT NULL,
  berakhir TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS donations (
  id TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  donor_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  jumlah INTEGER NOT NULL,
  metode TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Bank Sampah -----
CREATE TABLE IF NOT EXISTS waste_records (
  id TEXT PRIMARY KEY,
  resident_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  tanggal TEXT NOT NULL,
  jenis TEXT NOT NULL,
  berat REAL NOT NULL DEFAULT 0,
  nilai INTEGER NOT NULL,
  tipe TEXT NOT NULL CHECK (tipe IN ('setor','tarik')),
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX IF NOT EXISTS idx_waste_resident ON waste_records(resident_id);

-- ----- Visitor Management -----
CREATE TABLE IF NOT EXISTS visitors (
  id TEXT PRIMARY KEY,
  host_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  nama TEXT NOT NULL,
  keperluan TEXT NOT NULL,
  tanggal TEXT NOT NULL,
  jam TEXT NOT NULL,
  pin TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Menunggu' CHECK (status IN ('Menunggu','Di Dalam','Selesai')),
  checked_in_at INTEGER,
  checked_out_at INTEGER,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- UMKM Ads -----
CREATE TABLE IF NOT EXISTS umkm_ads (
  id TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  nama TEXT NOT NULL,
  jenis TEXT NOT NULL CHECK (jenis IN ('Produk','Jasa')),
  banner TEXT,
  promo TEXT NOT NULL,
  views INTEGER NOT NULL DEFAULT 0,
  clicks INTEGER NOT NULL DEFAULT 0,
  chats INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Broadcasts -----
CREATE TABLE IF NOT EXISTS broadcasts (
  id TEXT PRIMARY KEY,
  sender_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  judul TEXT NOT NULL,
  pesan TEXT NOT NULL,
  target_type TEXT NOT NULL,         -- 'Seluruh Warga' | 'Blok' | 'Lantai' | 'Unit' | 'Kelompok'
  target_value TEXT,                 -- e.g. 'A' | '03' | 'B-04-12' | 'PKK' | null
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Notifications (per-user inbox) -----
CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  type TEXT NOT NULL,                -- announcement | obituary | event | dues_new | dues_verified | dues_rejected | panic | booking_approved | booking_rejected | complaint_update | broadcast | campaign | visitor_status | chat_private | chat_group
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT,                         -- frontend route, e.g. /pengumuman, /chat?peer=X
  entity_id TEXT,                    -- related entity id
  read_at INTEGER,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id, read_at);

-- ----- Chat read receipts (track unread counts per conversation) -----
CREATE TABLE IF NOT EXISTS chat_reads (
  user_id TEXT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  conversation_key TEXT NOT NULL,    -- 'g:<group_id>' for groups or 'p:<peer_id>' for private
  last_read_at INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY (user_id, conversation_key)
);

-- ----- Dues settings (konfigurasi iuran per jenis) -----
CREATE TABLE IF NOT EXISTS dues_settings (
  jenis TEXT PRIMARY KEY,            -- IPL | Kebersihan | Keamanan | Dana Sosial
  enabled INTEGER NOT NULL DEFAULT 1,
  default_amount INTEGER NOT NULL DEFAULT 0,
  due_day INTEGER NOT NULL DEFAULT 10,   -- tanggal jatuh tempo tiap bulan (1-28)
  deskripsi TEXT,
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- App settings (key-value: payment config, dll.) -----
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ----- Expense categories (kategori penggunaan kas) -----
CREATE TABLE IF NOT EXISTS expense_categories (
  id TEXT PRIMARY KEY,
  nama TEXT NOT NULL UNIQUE,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);
